Repository lianaling/art-gallery-website, pull requests merged in 2021-08, with the labels that each got.

#22 Finished adding Identity authentication to the project
  Api/UserAuth.asmx.cs
  App_Start/IdentityConfig.cs
  App_Start/Startup.Auth.cs
  ArtGalleryWebsite.csproj
  Auth/Login.aspx.cs
  Auth/Register.aspx
  Auth/Register.aspx.cs
  Auth/Register.aspx.designer.cs
  Models/Entities/User.cs
  Models/Identity/Role.cs
  Models/Identity/User.cs
  Models/Identity/UserClaim.cs
  Models/Identity/UserLogin.cs
  Models/Identity/UserRole.cs
  Models/Identity/UserTable.cs
  Models/IdentityModels.cs
  Models/Queries/ArtQuery.cs
  Models/Queries/FavQuery.cs
  Models/Queries/UserQuery.cs
  Sql/tables/dbo.User.sql
  Startup.cs
  Utils/Database.cs
  Web.config
  packages.config
Labels: bug, backend, database

#24 Implemented `save` button
  Home.aspx
  Home.aspx.cs
  Home.aspx.designer.cs
  Models/Queries/FavQuery.cs
  Scripts/src/components/ArtCard.vue
  Scripts/src/pages/Home.vue
  Scripts/src/pages/User.vue
  Scripts/src/utils/helper.ts
  User.aspx.cs
Labels: frontend, backend, database

#26 Finished User Authentication
  Api/Auth.aspx
  Api/Auth.aspx.cs
  Api/Auth.aspx.designer.cs
  Api/UserAuth.asmx
  Api/UserAuth.asmx.cs
  App_Start/IdentityConfig.cs
  App_Start/Startup.Auth.cs
  ArtGalleryWebsite.csproj
  Auth/Login.aspx.cs
  Auth/Register.aspx
  Auth/Register.aspx.cs
  Auth/Register.aspx.designer.cs
  Dashboard.aspx.cs
  Models/ApiResponse.cs
  Models/AuthRole.cs
  Models/Error.cs
  Models/IdentityModels.cs
  Models/LoginResponse.cs
  Models/SessionData.cs
  Scripts/src/components/auth/AuthController.vue
  Scripts/src/pages/Master.vue
  Scripts/src/types/api.ts
  Scripts/src/types/state.ts
  Scripts/src/utils/api.ts
  Scripts/src/utils/auth.ts
  Scripts/src/utils/regex.ts
  Site.Master.cs
  Utils/Helper.cs
  Utils/IdentityHelper.cs
  Web.config
Labels: frontend, backend
