Repository lianaling/art-gallery-website, pull requests merged in 2021-07, with the labels that each got.

#6 Added Vue and Typescript
  ArtGalleryWebsite.csproj
  ArtGalleryWebsite.csproj.user
  Content/tailwind.css
  Default.aspx
  Home.aspx
  Home.aspx.cs
  Home.aspx.designer.cs
  README.md
  Scripts/dist/ArtCard.dist.js
  Scripts/dist/Helper.dist.js
  Scripts/dist/Home.dist.js
  Scripts/dist/HomePage.dist.js
  Scripts/dist/shims-vue.d.dist.js
  Scripts/src/HomePage.js
  Scripts/src/components/ArtCard.vue
  Scripts/src/pages/Home.vue
  Scripts/src/types/api.d.ts
  Scripts/src/utils/Helper.ts
  Site.Master
  package.json
  packages.config
  shims-vue.d.ts
  tailwind.config.js
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: documentation, enhancement

#7 Landing page upper part & some configs in `tailwind`
  Content/Site.css
  Content/tailwind.css
  Default.aspx
  Scripts/dist/ArtCard.dist.js
  Scripts/dist/Home.dist.js
  Scripts/dist/HomePage.dist.js
  Scripts/dist/api.d.dist.js
  Site.Master
  tailwind.config.js
Labels: enhancement

#14 Added utilities for querying database
  ArtGalleryWebsite.csproj
  Home.aspx
  Home.aspx.cs
  Home.aspx.designer.cs
  Models/Entities/Art.cs
  Models/Entities/Author.cs
  Models/ISqlParser.cs
  Models/LoginResponse.cs
  Models/Queries/ArtQuery.cs
  README.md
  Scripts/src/components/ArtCard.vue
  Scripts/src/pages/Home.vue
  Scripts/src/types/api.ts
  Scripts/src/types/model.ts
  Sql/data/insert_art.sql
  User.aspx.cs
  Utils/Database.cs
Labels: backend, database, enhancement
